import{a as S,S as E,i as l}from"./assets/vendor-Bt_EzQve.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const q="53058493-523f27a86fb9ebd113797df12",B="https://pixabay.com/api/";async function h(s,t=1,r=15){try{return(await S.get(B,{params:{key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r}})).data}catch(n){throw console.error("Error fetching images:",n),n}}const p=document.querySelector(".gallery"),y=document.querySelector(".load-more"),g=document.querySelector(".loader");let b=new E(".gallery a",{captionsData:"alt",captionDelay:250});function L(s){const t=s.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r.likes}</p>
          <p><b>Views:</b> ${r.views}</p>
          <p><b>Comments:</b> ${r.comments}</p>
          <p><b>Downloads:</b> ${r.downloads}</p>
        </div>
      </li>`).join("");p.insertAdjacentHTML("beforeend",t),b.refresh()}function M(){p.innerHTML="",b.refresh()}function w(){g.classList.add("visible")}function a(){g.classList.remove("visible")}function $(){y.classList.remove("hidden")}function v(){y.classList.add("hidden")}const m=document.querySelector(".form"),P=document.querySelector(".load-more");let c="",i=1;const d=15;let f=0;m.addEventListener("submit",async s=>{if(s.preventDefault(),c=m.elements["search-text"].value.trim(),!!c){i=1,M(),v(),w();try{const t=await h(c,i,d);if(f=t.totalHits,t.hits.length===0){l.info({title:"No results",message:"No images found."}),a();return}L(t.hits),a(),f>d&&$()}catch{a(),l.error({title:"Error",message:"Something went wrong!"})}}});P.addEventListener("click",async()=>{i+=1,w();try{const s=await h(c,i,d);L(s.hits),a();const t=Math.ceil(f/d);i>=t&&(v(),l.info({title:"End",message:"We're sorry, but you've reached the end of search results."}));const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch{a(),l.error({title:"Error",message:"Something went wrong!"})}});
//# sourceMappingURL=index.js.map
