import{a as S,S as E,i as a}from"./assets/vendor-Bt_EzQve.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const P="53058493-523f27a86fb9ebd113797df12",q="https://pixabay.com/api/";async function m(o,t=1,r=15){try{return(await S.get(q,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r}})).data}catch(n){throw console.error("Error fetching images:",n),n}}const g=document.querySelector(".gallery"),p=document.querySelector(".load-more"),y=document.querySelector(".loader"),M=new E(".gallery a",{captionsData:"alt",captionDelay:250});function b(o){if(!o||o.length===0)return;const t=o.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r.likes}</p>
          <p><b>Views:</b> ${r.views}</p>
          <p><b>Comments:</b> ${r.comments}</p>
          <p><b>Downloads:</b> ${r.downloads}</p>
        </div>
      </li>`).join("");g.insertAdjacentHTML("beforeend",t),M.refresh()}function B(){g.innerHTML=""}function L(){y.classList.remove("hidden")}function i(){y.classList.add("hidden")}function w(){p.classList.remove("hidden")}function v(){p.classList.add("hidden")}const h=document.querySelector(".form"),$=document.querySelector(".load-more");let l="",c=1;const d=15;let f=0;h.addEventListener("submit",async o=>{if(o.preventDefault(),l=h.elements.searchQuery.value.trim(),!l){a.warning({title:"Warning",message:"Please enter a search term."});return}c=1,B(),v(),L();try{const t=await m(l,c,d);if(f=t.totalHits,t.hits.length===0){a.info({title:"No results",message:"No images found."}),i();return}b(t.hits),i(),Math.ceil(f/d)>1?w():a.info({title:"End",message:"We're sorry, but you've reached the end of search results."})}catch{i(),a.error({title:"Error",message:"Something went wrong!"})}});$.addEventListener("click",async()=>{c+=1,v(),L();try{const o=await m(l,c,d);b(o.hits),i();const t=Math.ceil(f/d);c<t?w():a.info({title:"End",message:"We're sorry, but you've reached the end of search results."});const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch{i(),a.error({title:"Error",message:"Something went wrong!"})}});
//# sourceMappingURL=index.js.map
