import{a as E,S as P,i as n}from"./assets/vendor-Bt_EzQve.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const q="53058493-523f27a86fb9ebd113797df12",M="https://pixabay.com/api/";async function h(s,t=1,r=15){try{return(await E.get(M,{params:{key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r}})).data}catch(a){throw console.error("Error fetching images:",a),a}}const g=document.querySelector(".gallery"),p=document.querySelector(".load-more"),y=document.querySelector(".loader");let b=new P(".gallery a",{captionsData:"alt",captionDelay:250});function L(s){const t=s.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r.likes}</p>
          <p><b>Views:</b> ${r.views}</p>
          <p><b>Comments:</b> ${r.comments}</p>
          <p><b>Downloads:</b> ${r.downloads}</p>
        </div>
      </li>`).join("");g.insertAdjacentHTML("beforeend",t),b.refresh()}function B(){g.innerHTML="",b.refresh()}function w(){y.classList.add("visible")}function i(){y.classList.remove("visible")}function v(){p.classList.remove("hidden")}function S(){p.classList.add("hidden")}const m=document.querySelector(".search-form"),$=document.querySelector(".load-more");let c="",l=1;const d=15;let f=0;m.addEventListener("submit",async s=>{if(s.preventDefault(),c=m.elements.searchQuery.value.trim(),!c){n.warning({title:"Warning",message:"Please enter a search term."});return}l=1,B(),S(),w();try{const t=await h(c,l,d);if(f=t.totalHits,t.hits.length===0){n.info({title:"No results",message:"No images found."}),i();return}L(t.hits),i(),Math.ceil(f/d)>1?v():n.info({title:"End",message:"We're sorry, but you've reached the end of search results."})}catch{i(),n.error({title:"Error",message:"Something went wrong!"})}});$.addEventListener("click",async()=>{l+=1,S(),w();try{const s=await h(c,l,d);L(s.hits),i();const t=Math.ceil(f/d);l<t?v():n.info({title:"End",message:"We're sorry, but you've reached the end of search results."});const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch{i(),n.error({title:"Error",message:"Something went wrong!"})}});
//# sourceMappingURL=index.js.map
